#
#--------------------------------------------------------------------------
# Image Setup
#--------------------------------------------------------------------------
#

FROM php:5.6-fpm

# Set Environment Variables
ENV DEBIAN_FRONTEND noninteractive

RUN set -eux; \
    apt-get update; \
    apt-get upgrade -y; \
    apt-get install -y --no-install-recommends \
    curl \
    libmemcached-dev \
    libz-dev \
    libpq-dev \
    libjpeg-dev \
    libpng-dev \
    libfreetype6-dev \
    libssl-dev \
    libmcrypt-dev; \
    # cleanup
    rm -rf /var/lib/apt/lists/*

RUN set -eux; \
    docker-php-ext-install mcrypt; \
    docker-php-ext-install pdo_pgsql; \
    docker-php-ext-configure gd \
    --enable-gd-native-ttf \
    --with-jpeg-dir=/usr/lib \
    --with-freetype-dir=/usr/include/freetype2; \
    docker-php-ext-install gd; \
    php -r 'var_dump(gd_info());'

RUN set -xe; \
    apt-get update -yqq && \
    pecl channel-update pecl.php.net && \
    apt-get install -yqq \
    apt-utils libzip-dev zip unzip && \
    docker-php-ext-configure zip --with-libzip; \
    docker-php-ext-install zip && \
    php -m | grep -q 'zip'

###########################################################################
# pgsql client
###########################################################################

RUN \
    # Create folders if not exists (https://github.com/tianon/docker-brew-debian/issues/65)
    mkdir -p /usr/share/man/man1 && \
    mkdir -p /usr/share/man/man7 && \
    # Install the pgsql client
    apt-get install -y postgresql-client

###########################################################################
# PHP REDIS EXTENSION
###########################################################################
RUN if [ $(php -r "echo PHP_MAJOR_VERSION;") = "5" ]; then \
    pecl install -o -f redis-4.3.0; \
    else \
    pecl install -o -f redis; \
    fi \
    && rm -rf /tmp/pear \
    && docker-php-ext-enable redis

###########################################################################
# bcmath:
###########################################################################

RUN docker-php-ext-install bcmath

###########################################################################
# Image optimizers:
###########################################################################

USER root

RUN apt-get install -y jpegoptim optipng pngquant gifsicle

###########################################################################
# ImageMagick:
###########################################################################

USER root

RUN apt-get install -y libmagickwand-dev imagemagick && \
    pecl install imagick && \
    docker-php-ext-enable imagick

###########################################################################
# ping:
###########################################################################

USER root

RUN apt-get -y install inetutils-ping

###########################################################################
# Check PHP version:
##################################################################S#########

RUN set -xe; php -v | head -n 1 | grep -q "PHP 5.6."